name: ci
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add installation steps for Python dependencies
      - name: Install Python dependencies
        run: |
          pip install kivy kivymd pillow numpy plyer pdftotext gTTS keras googletrans
          pip install --upgrade cython  # Ensure cython is updated
          pip install buildozer         # If buildozer is a Python dependency

      # Add installation steps for system-level dependencies
      - name: Install system-level dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0 \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good libsqlite3-dev sqlite3 \
            bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev \
            liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev \
            libffi-dev libtool autoconf \
            libpoppler-cpp-dev  # Install poppler development files

      # Continue with your existing steps
    
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashfiles('buildozer.spec') }}

      - name: Cache Buildozer
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashfiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: artemsbulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Build app with Buildozer
        run:  |
            buildozer android debug --log_level=2

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
